#!/usr/bin/env bash
# setup.sh — configure MediaDesk email credentials

set -e

CONFIG_DIR="$HOME/.config/mediadesk-email"
CONFIG_FILE="$CONFIG_DIR/.env"

echo ""
echo "=== MediaDesk Email Skill Setup ==="
echo ""

mkdir -p "$CONFIG_DIR"

read -p "IMAP Host [mail.privateemail.com]: " IMAP_HOST
IMAP_HOST="${IMAP_HOST:-mail.privateemail.com}"

read -p "IMAP Port [993]: " IMAP_PORT
IMAP_PORT="${IMAP_PORT:-993}"

read -p "Email address: " IMAP_USER

read -s -p "Password: " IMAP_PASS
echo ""

read -p "SMTP Host [mail.privateemail.com]: " SMTP_HOST
SMTP_HOST="${SMTP_HOST:-mail.privateemail.com}"

read -p "SMTP Port [465]: " SMTP_PORT
SMTP_PORT="${SMTP_PORT:-465}"

cat > "$CONFIG_FILE" <<EOF
# MediaDesk Email Skill Configuration
# Generated by setup.sh — do not commit this file

# IMAP (receiving)
IMAP_HOST=$IMAP_HOST
IMAP_PORT=$IMAP_PORT
IMAP_USER=$IMAP_USER
IMAP_PASS=$IMAP_PASS
IMAP_TLS=true
IMAP_REJECT_UNAUTHORIZED=true
IMAP_MAILBOX=INBOX

# SMTP (sending)
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_SECURE=true
SMTP_USER=$IMAP_USER
SMTP_PASS=$IMAP_PASS
SMTP_FROM=$IMAP_USER
SMTP_REJECT_UNAUTHORIZED=true
EOF

# Lock down permissions — owner read/write only
chmod 600 "$CONFIG_FILE"

echo ""
echo "Config saved to $CONFIG_FILE (permissions: 600)"
echo ""
echo "Installing dependencies..."
npm install --silent

echo ""
echo "Testing IMAP connection..."
node scripts/imap.js list-mailboxes && echo "IMAP OK" || echo "IMAP connection failed — check your credentials."

echo ""
echo "Testing SMTP connection..."
node scripts/smtp.js test || echo "SMTP connection failed — check your credentials."

echo ""
echo "Setup complete."
